eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: hystrix-service
server:
  port: 8876



feign:
  hystrix:
    enabled: true
