eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




server:
  port: 8765
spring:
  application:
    name: eureka-client
