spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: /user

---
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      discovery:
        enabled: true
        service-id: config-server
      enabled: true
      fail-fast: true
      profile: dev
    consul:
      host: localhost
      port: 8500
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: config-client-${server.port}
        service-name: config-client

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"